Add files via upload

diff --git a/CryApp/uninstall b/CryApp/uninstall
--- a/CryApp/uninstall
+++ b/CryApp/uninstall
@@ -1,12 +1,46 @@
 #!/bin/bash
 
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
+#Variables
+AppName="MyApp"
+RepoUrl="https://example.com/$AppName"
+export PW_PREFIX="$HOME/.local/share/pi-ware"
+PACMANG="$(cat $PW_PREFIX/inst-pref)"
+fwe=""
+ers=""
 
+#Functions
 function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
+  echo -e "\e[91m$1\e[39m"
+  if [ "$2" == "exit" ]; then
+    exit 1
+  else
+    fwe="1"
+    ers+="$1"
+  fi
 }
-"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1
+
+function warning {
+  echo -e "\e[91m$2\e[39m"
+  sleep "$1"
+}
+
+#Main
+warning 5 "Warning: Uninstall $AppName will remove any saved data associated with $AppName. /n To cancel press CTRL + C in the next 5 seconds."
+echo "Uninstalling $AppName"
+#Remove AppNames's folder
+rm -rf ~/CryApp || error 'Failed to uninstall folder'
+sudo rm -f ~/.local/share/applications/CryApp || error 'Failed to unistall app'
+#Inform user that the uninstall has finished
+#Check if finished with errors
+if [ "${fwe}" == "1" ]; then
+  echo "This script finished with errors, Here are the errors: ${ers}"
+  exit 1
+elif [ "${fwe}" == "0" ]; then
+  echo "Successfully uninstalled $AppName."
+  echo "Closing in 5 seconds."
+  sleep 5s
+  exit 0
+fi
 
 rm -rf ~/CryApp || error 'Failed to uninstall folder'
 sudo rm -f ~/.local/share/applications/CryApp || error 'Failed to unistall app'
